# Generated by Django 4.2.11 on 2024-04-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
